application_conf:
  host: 0.0.0.0
  port: 8081
  meeting_no_length: 8
database_conf:
  # sqlite:
  # driver_type: sqlite
  # destination: server.db
  # destination: bak.db

  # postgres:
  driver_type: postgres
  destination: postgres://postgres:postgres@0.0.0.0:5432/postgres?sslmode=disable
jwt_conf:
  secret: "secret"
  expiration: 360000
